### ISSUE TITLE
Merge Xenon v3 examples repo

### ISSUE THREAD

**Issue by sverhoeven** [xenon-middleware/xenon-examples#89]
Merge content of https://github.com/jspaaks/xenon-examples repo into this repo.

**Comment by jspaaks** [comment]
Hmm i was planning on transferring but somebody just made a bunch of some issues... wanna try moving the issues? see if that works? It was a beta feature not too long ago.

**Comment by jspaaks** [comment]
Turns out I can't move issues to my repo for some reason. Changed the plan to include the other repo's history here instead (avoids transfer). 

You said you wanted a release before merging, I assumed you meant this repo. So I prepared this https://github.com/xenon-middleware/Xenon-examples/releases/tag/untagged-50a33cc46e2cec036dc1 Let me know what you think.

You also said you preferred to have only new contents, so I made changes to the branch here and made a PR https://github.com/xenon-middleware/Xenon-examples/pull/90

**Comment by sverhoeven** [comment]
https://github.com/xenon-middleware/Xenon-examples/releases/tag/1.0.6 is already the release I wanted to have. 

You can delete https://github.com/xenon-middleware/Xenon-examples/releases/tag/untagged-50a33cc46e2cec036dc1

**Comment by jspaaks** [comment]
deleted the draft release

**Comment by jspaaks** [comment]
all done thanks for merging #90
